// <auto-generated />
using CityInfo.API.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CityInfo.API.Migrations
{
    [DbContext(typeof(CityInfoContext))]
    [Migration("20240814131758_AddUserDetailsTable")]
    partial class AddUserDetailsTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.7");

            modelBuilder.Entity("CityInfo.API.Entities.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Description")
                        .HasDatabaseName("IX_Cities_Description");

                    b.HasIndex("Name")
                        .HasDatabaseName("IX_Cities_Name");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "It is known for its Mughal architecture and cuisine.",
                            Name = "Lucknow"
                        },
                        new
                        {
                            Id = 2,
                            Description = "The financial capital of India, famous for Bollywood.",
                            Name = "Mumbai"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Known for its cultural heritage and colonial architecture.",
                            Name = "Kolkata"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Famous for its palaces and the pink buildings in the old city.",
                            Name = "Jaipur"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Known for its beaches and Dravidian-style temples.",
                            Name = "Chennai"
                        });
                });

            modelBuilder.Entity("CityInfo.API.Entities.PointOfInterest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CityId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.ToTable("PointOfInterests");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CityId = 1,
                            Description = "The most visited urban park.",
                            Name = "Central Park"
                        },
                        new
                        {
                            Id = 2,
                            CityId = 1,
                            Description = "A 103-story skyscraper located in midtown Manhattan.",
                            Name = "Empire State Building"
                        },
                        new
                        {
                            Id = 3,
                            CityId = 2,
                            Description = "A historic fort and UNESCO World Heritage site.",
                            Name = "Red Fort"
                        },
                        new
                        {
                            Id = 4,
                            CityId = 2,
                            Description = "A war memorial and popular tourist spot.",
                            Name = "India Gate"
                        },
                        new
                        {
                            Id = 5,
                            CityId = 3,
                            Description = "A famous botanical garden with a glass house.",
                            Name = "Lalbagh Botanical Garden"
                        },
                        new
                        {
                            Id = 6,
                            CityId = 3,
                            Description = "A palace known for its Tudor-style architecture.",
                            Name = "Bangalore Palace"
                        },
                        new
                        {
                            Id = 7,
                            CityId = 4,
                            Description = "A large marble building and museum.",
                            Name = "Victoria Memorial"
                        },
                        new
                        {
                            Id = 8,
                            CityId = 4,
                            Description = "A cantilever bridge over the Hooghly River.",
                            Name = "Howrah Bridge"
                        },
                        new
                        {
                            Id = 9,
                            CityId = 5,
                            Description = "The longest natural urban beach in India.",
                            Name = "Marina Beach"
                        },
                        new
                        {
                            Id = 10,
                            CityId = 5,
                            Description = "A famous Hindu temple dedicated to Lord Shiva.",
                            Name = "Kapaleeshwarar Temple"
                        });
                });

            modelBuilder.Entity("CityInfo.API.Entities.UserDetails", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("UserDetails");
                });

            modelBuilder.Entity("CityInfo.API.Entities.PointOfInterest", b =>
                {
                    b.HasOne("CityInfo.API.Entities.City", "City")
                        .WithMany("PointsOfInterest")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("CityInfo.API.Entities.City", b =>
                {
                    b.Navigation("PointsOfInterest");
                });
#pragma warning restore 612, 618
        }
    }
}
